/***************************************************************************************************
 * @file MainMCU.c
 * @brief Start and main loop of the MCU. Keeps the autogenerated code from STM32 separated from the 
 * human written code.
 * 
 * @project MIDDS
 * @version 1.0
 * @date    2024-12-07
 * @author  @dabecart
 * 
 * @license This project is licensed under the MIT License - see the LICENSE file for details.
***************************************************************************************************/

#include "MainMCU.h"

HWTimers hwTimers;
UART_HandleTypeDef* huart;

void initMCU(TIM_HandleTypeDef* htim1,
             TIM_HandleTypeDef* htim2, 
             TIM_HandleTypeDef* htim3, 
             TIM_HandleTypeDef* htim4,
             UART_HandleTypeDef* huart2)
{
    initHWTimers(&hwTimers, htim1, htim2, htim3, htim4);
    huart = huart2;

    startHWTimers(&hwTimers);

    // Wait for a second and try to grab any SYNC pulse.
    HAL_Delay(2000);

    if(hwTimers.measuredPeriodHighSYNC != 0 || hwTimers.measuredPeriodLowSYNC != 0) {
        // It is using a SYNC pulse, clear all current buffers.
        clearHWTimer(&hwTimers.htim1);
        clearHWTimer(&hwTimers.htim2);
        clearHWTimer(&hwTimers.htim3);
        clearHWTimer(&hwTimers.htim4);
    }
}

void loopMCU() {
    static char outMsg[1024];
    
    if(readyToPrintHWTimer(&hwTimers.htim1)) {
        uint16_t msgSize = sprintfHWTimer(&hwTimers.htim1, outMsg, sizeof(outMsg));
        HAL_UART_Transmit(huart, (uint8_t*) outMsg, msgSize, 1000);
    } 

    if(readyToPrintHWTimer(&hwTimers.htim2)) {
        uint16_t msgSize = sprintfHWTimer(&hwTimers.htim2, outMsg, sizeof(outMsg));
        HAL_UART_Transmit(huart, (uint8_t*) outMsg, msgSize, 1000);
    } 

    if(readyToPrintHWTimer(&hwTimers.htim3)) {
        uint16_t msgSize = sprintfHWTimer(&hwTimers.htim3, outMsg, sizeof(outMsg));
        HAL_UART_Transmit(huart, (uint8_t*) outMsg, msgSize, 1000);
    } 

    if(readyToPrintHWTimer(&hwTimers.htim4)) {
        uint16_t msgSize = sprintfHWTimer(&hwTimers.htim4, outMsg, sizeof(outMsg));
        HAL_UART_Transmit(huart, (uint8_t*) outMsg, msgSize, 1000);
    } 
}
