/***************************************************************************************************
 * @file MainMCU.c
 * @brief Start and main loop of the MCU. Keeps the autogenerated code from STM32 separated from the 
 * human written code.
 * 
 * @project MIDDS
 * @version 1.0
 * @date    2024-12-07
 * @author  @dabecart
 * 
 * @license This project is licensed under the MIT License - see the LICENSE file for details.
***************************************************************************************************/

#include "MainMCU.h"

HWTimers hwTimers;
extern USBD_HandleTypeDef hUsbDeviceFS;

void initMCU(TIM_HandleTypeDef* htim1,
             TIM_HandleTypeDef* htim2, 
             TIM_HandleTypeDef* htim3, 
             TIM_HandleTypeDef* htim4)
{
    initHWTimers(&hwTimers, htim1, htim2, htim3, htim4);

    startHWTimers(&hwTimers);

    // Wait for a few seconds and try to grab any SYNC pulse.
    HAL_Delay(2000);

    if(hwTimers.measuredPeriodHighSYNC != 0 || hwTimers.measuredPeriodLowSYNC != 0) {
        // It is using a SYNC pulse, clear all current buffers.
        for(uint16_t i = 0; i < HW_TIMER_CHANNEL_COUNT; i++) {
            clearHWTimer(hwTimers.channels+i);
        }
    }

    // Wait until the USB gets connected.
    while(hUsbDeviceFS.dev_state != USBD_STATE_CONFIGURED){}

}

void loopMCU() {
    static uint8_t outMsg[1024];
    
    for(uint16_t i = 0; i < HW_TIMER_CHANNEL_COUNT; i++) {
        if(readyToPrintHWTimer(hwTimers.channels + i)) {
            uint16_t msgLen = generateMonitorMessage(hwTimers.channels + i, outMsg, sizeof(outMsg));
            while(CDC_Transmit_FS(outMsg, msgLen) == USBD_BUSY){}
        }
    }

}
