/***************************************************************************************************
 * @file MainMCU.c
 * @brief Start and main loop of the MCU. Keeps the autogenerated code from STM32 separated from the 
 * human written code.
 * 
 * @project MIDDS
 * @version 1.0
 * @date    2024-12-07
 * @author  @dabecart
 * 
 * @license This project is licensed under the MIT License - see the LICENSE file for details.
***************************************************************************************************/

#ifndef MAIN_MCU_h
#define MAIN_MCU_h

#include "stm32g4xx_hal.h"

#include "main.h"

#include "HWTimers.h"
#include "Comms.h"
#include "ChannelController.h"
#include "ST7735.h"

// vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv DEFINES vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
#define MCU_TX_IN_ASCII 0

#define MCU_FREQUENCY 160000000ULL

#define MCU_CHANNEL_PRINT_INTERVAL 10 // ms

#define WAIT_UNTIL_USB_CONNECTION 1

/**************************************** FUNCTION *************************************************
 * @brief Fetches the peripheral handlers from main.c and takes it to the non-autogenerated code.
 * @param htim1. Defined in main.c.
 * @param htim2. Defined in main.c.
 * @param htim3. Defined in main.c.
 * @param htim4. Defined in main.c.
 * @param hspi1. Defined in main.c.
***************************************************************************************************/
void initMCU(TIM_HandleTypeDef* htim1,
             TIM_HandleTypeDef* htim2, 
             TIM_HandleTypeDef* htim3, 
             TIM_HandleTypeDef* htim4,
             SPI_HandleTypeDef* hspi1);

/**************************************** FUNCTION *************************************************
 * @brief Main loop of the MCU.
***************************************************************************************************/
void loopMCU();

// vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv EXTERNAL VARIABLES vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
extern HWTimers hwTimers;
extern ChannelController chCtrl;

#endif // MAIN_MCU_h