/***************************************************************************************************
 * @file MainMCU.c
 * @brief Start and main loop of the MCU. Keeps the autogenerated code from STM32 separated from the 
 * human written code.
 * 
 * @project MIDDS
 * @version 1.0
 * @date    2024-12-07
 * @author  @dabecart
 * 
 * @license This project is licensed under the MIT License - see the LICENSE file for details.
***************************************************************************************************/

#include "MainMCU.h"

HWTimers hwTimers;
ChannelController chCtrl;

void initMCU(TIM_HandleTypeDef* htim1,
             TIM_HandleTypeDef* htim2, 
             TIM_HandleTypeDef* htim3, 
             TIM_HandleTypeDef* htim4,
             SPI_HandleTypeDef* hspi1)
{
    initComms(WAIT_UNTIL_USB_CONNECTION);

    ST7735_Init(hspi1);
    ST7735_FillScreenFast(ST7735_BLACK);

    initHWTimers(&hwTimers, htim1, htim2, htim3, htim4);

    startHWTimers(&hwTimers);

    initChannelController(&chCtrl, hspi1);

    // // Wait for a few seconds and try to grab any SYNC pulse.
    // HAL_Delay(3000);

    // if(hwTimers.measuredPeriodHighSYNC != 0 || hwTimers.measuredPeriodLowSYNC != 0) {
    //     // It is using a SYNC pulse, clear all current buffers.
    //     for(uint16_t i = 0; i < HW_TIMER_CHANNEL_COUNT; i++) {
    //         clearHWTimer(hwTimers.channels+i);
    //     }
    // }
}

void loopMCU() {
    // Receive commands and generate the responses.
    receiveData();

    // Generate the recurrent messages.
    ChannelMessage tempMsg = {};
    for(uint16_t i = 0; i < HW_TIMER_CHANNEL_COUNT; i++) {
        if(readyToPrintHWTimer(hwTimers.channels + i)) {
            tempMsg.monitor = hwTimers.channels + i;
            encodeGPIOMessage(GPIO_MSG_MONITOR, tempMsg); 
        }
    }

    // Send the data.
    sendData();
}
